---
- name: Ensure builds directory exists
  file:
    path: "{{ build_dir }}"
    state: directory
 
- name: Ensure profile directory exists
  file:
    path: "{{ build_dir }}/{{ build_profile }}-bp/"
    state: directory

- name: Determine latest stage3
  get_url:
    url: "http://distfiles.gentoo.org/releases/amd64/autobuilds/latest-stage3-amd64-systemd.txt"
    dest: "{{ build_dir }}/{{ build_profile }}-bp/"
    force: yes

- name: set seeds_version_stamp
  set_fact:
    seeds_version_stamp: "{{ lookup('file', '{{ build_dir }}/{{ build_profile }}-bp/latest-stage3-amd64-systemd.txt') | regex_search('[0-9]{8}.tar.bz2') | regex_replace('.tar.bz2','') }}"

- name: Show latest stage3 snapshot
  debug: msg="Latest stage3 stamp is {{ seeds_version_stamp }}"
  when: download_latest_stage3|bool

- name: Get stage3 seed
  get_url:
    url: "http://distfiles.gentoo.org/releases/amd64/autobuilds/current-stage3-amd64-systemd/stage3-amd64-systemd-{{ seeds_version_stamp }}.tar.bz2"
    dest: "{{ build_dir }}/{{ build_profile }}-bp/"
  when: download_latest_stage3|bool

- name: Unarchive stage3
  unarchive:
    src: "{{ build_dir }}/{{ build_profile }}-bp/stage3-amd64-systemd-{{ seeds_version_stamp }}.tar.bz2"
    dest: "{{ build_dir }}/{{ build_profile }}-bp/"
    creates: "{{ build_dir }}/{{ build_profile }}-bp/etc/issue"

- name: Copy resolv.conf
  command: cp -L /etc/resolv.conf {{ build_dir }}/{{ build_profile }}-bp/etc/

- name: Clean portage default conf
  block:
    - name: Remove portage directory
      file: state=absent path="{{ build_dir }}/{{ build_profile }}-bp/etc/portage"
    - name: Create clean portage directory
      file: state=directory path="{{ build_dir }}/{{ build_profile }}-bp/etc/portage"

- name: Deploy portage configuration
  synchronize:
    src: "{{ build_profile }}-portage/"
    dest: "{{ build_dir }}/{{ build_profile }}-bp/etc/portage"

- name: Set make number of jobs 
  replace:
    path: "{{ build_dir }}/{{ build_profile }}-bp/etc/portage/make.conf"
    regexp: '^(MAKEOPTS=)(.*)$'
    replace: '\1"-j{{ number_of_make_jobs }}"'

- name: Install lightttpd on build server
  portage:
    package: www-servers/lighttpd
    state: latest

- name: Configure lightttpd to export bin packages
  replace:
    path: /etc/lighttpd/lighttpd.conf
    regexp: '^#(\s+\"mod_alias\",)$'
    replace: '\1'
    backup: yes

- name: Enable directory listing
  replace:
    path: /etc/lighttpd/lighttpd.conf
    regexp: '^#(\s+dir-listing.activate\s+=\s+\"enable\")$'
    replace: '\1'

- name: Bind lighttpd to default address
  replace:
    path: /etc/lighttpd/lighttpd.conf
    regexp: '^#(\s+server\.bind\s+=\s)(.*)$'
    replace: '\1"{{ ansible_default_ipv4.address }}"'

- name: "Create alias url for {{ build_profile }}"
  lineinfile:
    path: /etc/lighttpd/lighttpd.conf
    line: 'alias.url = ( "/packages-{{ build_profile }}" => "{{ build_dir }}/{{ build_profile }}-bp/usr/portage/packages/" )'
  notify:
    - Start and enable lighttpd service
